name: gitleaks

on: [push, pull_request, workflow_call]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master
        with:
          config-path: .gitleaks.toml